name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'issue-*'
  pull_request:
    branches:
      - main

jobs:
  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Python linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check-only .
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: pipenv run pytest

  solidity-lint:
    name: Solidity Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          bash -c "source ~/.bashrc && foundryup"
      - name: Run forge fmt check
        run: forge fmt --check

  solidity-tests:
    name: Solidity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          bash -c "source ~/.bashrc && foundryup"
      - name: Run tests
        run: forge test

  # solidity-coverage:
  #   name: Solidity Coverage (Disabled)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Coverage disabled: using Foundry (no Hardhat or solidity-coverage required)"